### Post create products
POST {{baseUrl}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tayna",
    "price": 28.10
}

###

GET {{baseUrl}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Marcelo Henrique Pinto",
    "price": 28.10
}


###

DELETE {{baseUrl}}/products/3
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{baseUrl}}/auth HTTP/1.1
Content-Type: application/json

{
    "password": "123",
    "username": "marcelo"
   
}

